#!/usr/bin/env python3
"""
extract_vial.py — CS2 Minneapolis Red Vial Pipeline (Sesión 2)
==============================================================
Extrae la red vial real desde OpenStreetMap y la exporta como un archivo JS
listo para el visualizador Leaflet (overlay encima del mapa de zonificación).

Salida (`visualizer/datos_vial.js`):
    const DATA_VIAL = {
      "highway":    [{ id, name, coords: [[lat,lon],...], cs2_key, cs2 }, ...],
      "major":      [...],
      "minor":      [...],
      "local":      [...],
      "pedestrian": [...],
      "bike":       [...],
    };
    const DATA_VIAL_META = { bbox, generated_at, total_features };

Uso:
    cd src
    uv run extract_vial.py
    uv run extract_vial.py --bbox "44.86,-93.38,45.05,-93.17"
    uv run extract_vial.py --out ../visualizer/datos_vial.js
"""

import argparse
import json
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

from overpass_client import query_with_retry
from vial_classifiers import classify_highway
from vial_zones import VIAL_LABELS, MINNEAPOLIS_BBOX, build_vial_query


# ── Geometry helpers ─────────────────────────────────────────────────────────

def linestring_from_way(element: dict) -> list | None:
    """
    Extraer la geometría LineString de un elemento Overpass `way`.

    Devuelve [[lat, lon], ...] con ≥2 puntos, o None si la way es degenerada
    (sin geometry, con <2 puntos, o sin tag highway).
    """
    geom = element.get("geometry") or []
    if len(geom) < 2:
        return None
    return [[pt["lat"], pt["lon"]] for pt in geom]


# ── Output assembly ──────────────────────────────────────────────────────────

def make_feature(el: dict, coords: list, cs2_key: str) -> dict:
    tags = el.get("tags") or {}
    return {
        "id": el["id"],
        "name": tags.get("name", "") or tags.get("ref", ""),
        "coords": coords,
        "cs2_key": cs2_key,
        "cs2": VIAL_LABELS[cs2_key],
        # bridge=yes se preserva como flag para que el visualizer pueda
        # darle un weight +0.5 si lo desea
        "bridge": tags.get("bridge") == "yes",
    }


# ── Main pipeline ────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Extract OSM road network for CS2 Minneapolis (Sesión 2)"
    )
    parser.add_argument(
        "--bbox",
        default=MINNEAPOLIS_BBOX,
        help=f"Bounding box 'south,west,north,east' (default: {MINNEAPOLIS_BBOX})",
    )
    parser.add_argument(
        "--out",
        default="../visualizer/datos_vial.js",
        help="Output .js file path",
    )
    args = parser.parse_args()

    bbox = args.bbox
    out_path = Path(args.out)
    query = build_vial_query(bbox)

    print("CS2 Minneapolis Vial Extractor — Sesión 2")
    print(f"Bounding Box : {bbox}")
    print(f"Output       : {out_path}\n")

    # ── Step 1: Download highway ways ────────────────────────────────────────
    print("[1/2] Downloading highway ways from Overpass...")
    result = query_with_retry(query, "vial")
    elements = result.get("elements", [])
    print(f"      raw ways: {len(elements)}")

    # ── Step 2: Classify & bucket ────────────────────────────────────────────
    print("\n[2/2] Classifying ways into CS2 categories...")
    buckets: dict[str, list] = defaultdict(list)
    skipped_geom = 0
    skipped_class = 0

    for el in elements:
        coords = linestring_from_way(el)
        if coords is None:
            skipped_geom += 1
            continue
        cs2_key = classify_highway(el.get("tags") or {})
        if cs2_key is None:
            skipped_class += 1
            continue
        buckets[cs2_key].append(make_feature(el, coords, cs2_key))

    total = sum(len(v) for v in buckets.values())

    # ── Summary ──────────────────────────────────────────────────────────────
    print()
    print(f"  {'category':<14}  count")
    print(f"  {'-'*14}  {'-'*6}")
    for key in VIAL_LABELS:
        n = len(buckets.get(key, []))
        print(f"  {key:<14}  {n:>6}")
    print(f"  {'-'*14}  {'-'*6}")
    print(f"  {'TOTAL':<14}  {total:>6}")
    print(f"\n  skipped (no geometry):   {skipped_geom}")
    print(f"  skipped (no classifier): {skipped_class}")

    # ── Write output ─────────────────────────────────────────────────────────
    meta = {
        "bbox": bbox,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "total_features": total,
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as f:
        f.write("// Auto-generated by extract_vial.py — do not edit manually\n")
        f.write(f"// {meta['generated_at']} — {total} features — bbox {bbox}\n\n")
        # Un bucket por categoría
        f.write("const DATA_VIAL = ")
        json.dump(dict(buckets), f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n\n")
        f.write("const DATA_VIAL_META = ")
        json.dump(meta, f, ensure_ascii=False)
        f.write(";\n")

    print(f"\n[OK] Wrote {out_path} ({out_path.stat().st_size / 1024:.1f} KB)")


if __name__ == "__main__":
    main()
